#!/usr/bin/env node

import fs from 'node:fs'
import path from 'node:path'

const ROOT = process.cwd()

function parseArgs(argv) {
  const out = {}
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]
    if (!arg.startsWith('--')) continue
    const key = arg.slice(2)
    const next = argv[i + 1]
    if (!next || next.startsWith('--')) {
      out[key] = 'true'
      continue
    }
    out[key] = next
    i += 1
  }
  return out
}

function toToolId(input) {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function toPascalCase(value) {
  return value
    .split(/[^a-zA-Z0-9]/g)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true })
}

function writeFileIfMissing(filePath, content) {
  if (fs.existsSync(filePath)) {
    throw new Error(`File already exists: ${filePath}`)
  }
  fs.writeFileSync(filePath, content, 'utf8')
}

function updateRegistry({ toolId, manifestVarName }) {
  const registryPath = path.join(ROOT, 'lib', 'tool-registry.ts')
  const source = fs.readFileSync(registryPath, 'utf8')

  const importLine = `import { ${manifestVarName} } from '@/tools/${toolId}/manifest'`
  if (source.includes(importLine)) return

  const importMarker = '// TOOL_IMPORTS_END'
  const registryMarker = '// TOOL_REGISTRY_END'
  if (!source.includes(importMarker) || !source.includes(registryMarker)) {
    throw new Error('tool-registry.ts is missing scaffold markers')
  }

  const withImport = source.replace(
    importMarker,
    `${importLine}\n${importMarker}`,
  )

  const withRegistryEntry = withImport.replace(
    registryMarker,
    `  ${manifestVarName},\n  ${registryMarker}`,
  )

  fs.writeFileSync(registryPath, withRegistryEntry, 'utf8')
}

function main() {
  const args = parseArgs(process.argv.slice(2))
  const rawName = args.name || args.n
  if (!rawName) {
    console.error('Usage: npm run tool:new -- --name "seo-assistant"')
    process.exit(1)
  }

  const toolId = toToolId(rawName)
  if (!toolId) {
    console.error('Invalid tool name.')
    process.exit(1)
  }

  const category = args.category || 'custom'
  const displayName = args.title || toPascalCase(toolId)
  const description = args.description || 'Tool generated by scaffold script.'
  const icon = args.icon || 'Wrench'
  const tagList = (args.tags || 'custom').split(',').map((item) => item.trim()).filter(Boolean)

  const toolDir = path.join(ROOT, 'tools', toolId)
  const apiDir = path.join(ROOT, 'app', 'api', 'tools', toolId)
  ensureDir(toolDir)
  ensureDir(apiDir)

  const componentName = `${toPascalCase(toolId)}Tool`
  const manifestVarName = `${toPascalCase(toolId).charAt(0).toLowerCase()}${toPascalCase(toolId).slice(1)}Tool`

  const componentPath = path.join(toolDir, 'component.tsx')
  const manifestPath = path.join(toolDir, 'manifest.ts')
  const routePath = path.join(apiDir, 'route.ts')

  const componentContent = `'use client'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

export function ${componentName}() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>${displayName}</CardTitle>
      </CardHeader>
      <CardContent className="text-sm text-muted-foreground">
        This tool is scaffolded. Replace this component with your actual UI.
      </CardContent>
    </Card>
  )
}
`

  const manifestContent = `import { ToolManifest } from '@/lib/tool-manifest'
import { ${componentName} } from './component'

export const ${manifestVarName}: ToolManifest = {
  id: '${toolId}',
  name: '${displayName}',
  description: '${description}',
  icon: '${icon}',
  category: '${category}',
  tags: ${JSON.stringify(tagList)},
  component: ${componentName},
  enabled: true,
  route: '/tools/${toolId}',
}
`

  const routeContent = `import { NextResponse } from 'next/server'
import { auth } from '@/auth'

export async function POST() {
  const session = await auth()
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  return NextResponse.json({
    message: '${toolId} API route scaffolded. Implement your business logic here.',
  })
}
`

  writeFileIfMissing(componentPath, componentContent)
  writeFileIfMissing(manifestPath, manifestContent)
  writeFileIfMissing(routePath, routeContent)
  updateRegistry({ toolId, manifestVarName })

  console.log(`Scaffolded tool "${toolId}"`)
  console.log(`- tools/${toolId}/component.tsx`)
  console.log(`- tools/${toolId}/manifest.ts`)
  console.log(`- app/api/tools/${toolId}/route.ts`)
}

main()
